version: "3"

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    tty: true
    stdin_open: true
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command:
      - "start-dev"
    networks:
      keycloak_network:
        ipv4_address: 172.16.0.2

networks:
  default:
    name: bridge
  keycloak_network:
    name: keycloak_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
